Shifted existing implementations to Optax and implemented Meta SGD
SforAiDl/jeta pull request #19
Opened 2022-06-27 19:31 UTC by AnirudhM1

- Optax optimizers are used instead of flax.optim
- Added Meta SGD

---

A point of concern in these implementations is initialization.
Standard flax initializations cause the model weights to explode and hence they have been manually scaled to a normal distribution with mean=0 & std=0.01. 

This explicit scaling might not work for all kinds of model architectures and hence some other form of initialization strategy must be used.

2022-07-03 07:52 UTC, threewisemonkeys-as requested changes
Some minor comments, otherwise looks good to me. 

@AnirudhM1 have you tried this out on any dataset?

2022-07-03 07:52 UTC, threewisemonkeys-as commented on jeta/opti_trainer.py
> +            tx (Optax Optimizer): Optax optimizer.
```suggestion
            tasks ((x_train, y_train), (x_test, y_test)): Batch of tasks to be trained on
```

2022-07-03 07:52 UTC, threewisemonkeys-as commented on jeta/opti_trainer.py
> +            tasks ((x_train, y_train), (x_test, y_test)): Batch of tasks to be trained on.
```suggestion
            tasks ((x_train, y_train), (x_test, y_test)): Batch of tasks to be evaluated on.
```

2022-07-03 11:35 UTC, AnirudhM1 commented
@threewisemonkeys-as Yes. I have tested this on the _Sin dataset_ as mentioned in the [Meta SGD paper](https://arxiv.org/abs/1707.09835) and have obtained results comparable to the ones reported in the paper for both MAML and Meta SGD.

2022-07-03 18:29 UTC, veds12 commented
Let's wait till #21 get's merged. Should take a couple of days. Till then, feel free to take a look at other issues :)

2022-07-16 17:37 UTC, veds12 commented
@AnirudhM1 PR #21 has been merged. Can you run the pre-commit and make sure all the tests pass

2022-07-17 23:17 UTC, AnirudhM1 commented
> ```python
> def __call__(self, x, train=True):
>     return nn.Dense(10)(x)
> ```

---

Here using the kwarg `train` is necessary regardless if it being used or not. This is because layers like `batchnorm` behave differently at train/test time and need some form of indicator. 
To make the interface consistent across all types of models, kwarg 'train' is assumed to be present in all models.

 

To enable consistent use of models, some minor changes have been made.
  
cc: @veds12 @threewisemonkeys-as

2022-07-18 07:06 UTC, veds12 commented
@AnirudhM1 Lint is still failing. Are you running pre-commit before pushing?

2022-07-18 19:01 UTC, merged